name: Build & Push Nonroot Container Image
on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set version latest
      if: github.ref == 'refs/heads/master'
      run: echo VERSION=latest-nonroot >> $GITHUB_ENV
    - name: Set version from tag
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo VERSION="$(echo ${GITHUB_REF#refs/tags/})-nonroot" >> $GITHUB_ENV
    - name: Push Image to ghcr.io
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        registry: ghcr.io
        name: "${{ github.repository }}:${{ env.VERSION }}"
        username: ${{ secrets.GITHUB_TOKEN }}
        password: ${{ secrets.GITHUB_TOKEN }}
        buildoptions: --target nonroot
