name: Test Nonroot
on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build image
      run: docker build --target nonroot -t test .
    - name: Run image
      run: docker run --rm test --help
